version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.6.1
    steps:
      - checkout
      - restore_cache:
        keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
          - yarn-deps
      - run:
        name: yarn install
        command: yarn install
      - save_cache:
        paths:
          - node_modules
        key: yarn-deps-{{ checksum "yarn.lock" }}
      - store_artifacts:
        path: yarn.lock
      - run:
          name: Build React App
          command: yarn build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
